name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  
  pull-requests: write
  id-token: write  

jobs:
  test:
    runs-on: ubuntu-latest  

    services:
      mongodb:
        image: mongo:latest  
        ports:
          - 27017:27017  

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # FIX PERMISSIONS: Make Jest executable
      - name: Fix jest permissions
        run: chmod +x node_modules/.bin/jest

      #  FIX LINE ENDINGS: Convert to Unix line endings 
      - name: Convert jest script to Unix line endings
        run: sudo apt-get install dos2unix && dos2unix node_modules/.bin/jest

      - name: Run Tests
        run: npm test
        env:
          MONGO_URI: mongodb://localhost:27017/testdb
